const STRINGS = {
  pomodoroTitleFocusSub : "It's time to",
  pomodoroTitleFocusMain : "focus!",
  pomodoroTitleShortBreakSub : "Take a deep",
  pomodoroTitleShortBreakMain : "breathe.",
  pomodoroTitleLongBreakSub: "Nice work!",
  pomodoroTitleLongBreakMain: "Relax :)",
  agendaTitle: "Daily Agenda",
  agendaHeading: "My Goals",
  addTaskBarDescription: "Set your next goal",
  settingsModalTitle: "Focus Mode",
  focusModeOffDescription: "Off",
  focusModeFlipDescription: "Flip Phone",
  focusModeLockdownDescription: "Lockdown",
  tutorialsTitle: "Tutorials",
  routinesTitle: "Routines",
  lockdownSnackbarMessage: "Lockdown Mode is currently active. Leaving the app will restart the timer!",
  flipPhoneSnackbarMessage: "Flip Mode is activated! Timer will be reset if the phone is not flipped upside down.",
  startSessionSnackbarMessage: "Please select a routine. Only one can be activated at a time.",
  intervalCompletedSnackbarMessage: "An interval has been completed, keep on going! Make sure to hydrate and refuel!",
  startSessionButton: "Start Session",
  exitSessionButton: "Exit Session",
  timerWorkCompletedAlertTitle: "Focused Session Completed 👏",
  timerWorkCompletedAlertMessage: "Congrats and nice work! Take a break :D",
  timerShortBreakCompletedAlertTitle: "The Break Has Ended ✏️",
  timerShortBreakCompletedAlertMessage: "Feeling Refreshed? Let's get back to work!",
  timerLongBreakCompletedAlertTitle: "The Break Has Ended 📖",
  timerLongBreakCompletedAlertMessage: "Let's keep working hard! You've got this!",
  timerResetAlertTitle: "Timer Reset ❌",
  timerResetFlipPhoneAlertMessage: "Phone was not flipped in time. Please start a new focused working session.",
  timerResetLockdownAlertMessage: "App was exited. Stay in the app for lockdown mode.",
  sessionEndedAlertTitle: "Session Has Ended! 🥳🎉",
  sessionEndedAlertMessage: "Great Work! You are amazing!",
  routineFormTitleEdit: "Edit Routine",
  routineFormTitleCreate: "Create Routine",
  routineFormSaveButton: "Save",
  routineFormSubheadingIntervals: "Intervals:",
  routineFormSubheadingTotalTime: "Total Time:",
  routineFormAddButton: "Add",
}

export default STRINGS;
